language: python

notifications:

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10

script:
  python manage.py test
